print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call a astronauts cavity?')
input()
print('A black hole!')
print()
print('Knock Knock.')
input()
print("Who's there?")
input()
print('Intuerrupting cow.')
input()
print('Intuerrupting cow wh', end=' ')
print('-MOO!')